### ISSUE TITLE
ERROR CANT DETERMINE GATEWAY PLEASE ENSURE PROPER NETWORK CONNECTIVITY

### ISSUE THREAD

**Issue by SERAF000VIRUS** [Subterfuge-Framework/Subterfuge#4]
I INSTALLED THIS NEW VERSION BUT HAD TO JUMP THROUGH A FEW HOOPS TO GET IT WORKING ON KALI 2.0 VITURALBOX. 

FIRST I HAD TO CHANGE TEMP_DIRS TO A TUPLE
THEN I HAD TO DELETE URLS.PYC AND REMOVE .DEFAULTS FROM URLS.PY 
THEN I HAD TO ADD IMPORT DJANGO, DJANGO.SETUP( ) TO THE ATTACKCTRL.PY

FINALLY I GOT EVERYTHING TO WORK WITH THE EXCEPTION OF THIS NEW ERROR IN THE BROWSER TERMINAL THAT SAYS CANT DETERMINE GATEWAY CHECK CONNECTIVITY. WHEN I AM CONNECTED TO A LOCAL WIFI

FURTHERMORE, IN THE TERMINAL WINDOW, IT SAYS WARNING NO ROUTE FOUND FOR IPV6 DESTINATION...

PLEASE HELP!!

**Comment by 0sm0s1z** [comment]
Is the vm in bridged mode, or is the network at to nat. Also what is the
actual gateway if it's nonstandard thatight help in troubleshooting.
Finally in the settings page you can turn off gateway auto discovery and
set the gateway manually (by typing in the ip address)

Let me know if that works for you. I'm aware of the kali 2.0 issues just
haven't had a chance to push an update for them.

**Comment by SERAF000VIRUS** [comment]
I have the network set to NAT but I have already tried using all other modes and none of the others worked. The farthest I get in executing the software is with it set to NAT. So using the others is not an option since it crashes the program.

I pretty sure the gateway is standard, although perhaps you may tell explicitly how to check if it is nonstandard

also, I have tried this on several different networks, and it did not work for either...

**Comment by 0sm0s1z** [comment]
With the network set to nat (that's an internal virtualization setting) the
attacking machine won't be able to communicate with victim computers and
the attack will fail.

Setting the gateway manually is probably your best bet. Setting the network
mode to bridged should be transparent to Subterfuge so that should cause
any errors.

Have you tried to capture credentials with it at all? It's possible that
the error is just incorrect. Also could you send me some screenshots of
your settings? I'll be able to let you know if it's configured oddly.
(Generally that wouldn't be a big issue, but we're in the middle of some
large changes at the moment, and it's caused some unexpected errors to crop
up.)

**Comment by SERAF000VIRUS** [comment]
so I will set the network to 'bridged adapter' mode then
if that does not work I will set it gateway ip manually which I obtained btw by router -n where flag is GU.
if this doesn't work I will come back in reply with some screenshots of the settings of the settings in the browser terminal...

**Comment by SERAF000VIRUS** [comment]
so I tried...
below is a screenshot of the terminal with the erros

the browser window just stops at ''' attack initializing''''

also, when I opened a new tab to test, the internet didn't work, odd, because the the browser terminal works but other tabs with internet dont'....


<img width="1043" alt="capture" src="https://cloud.githubusercontent.com/assets/14218999/9792854/f69a9f20-57a7-11e5-8dde-61e8a8c73ada.PNG">

**Comment by 0sm0s1z** [comment]
Well... that does look bad doesn't it!

On the internet piece. Subterfuge sometimes kills the local machine's
ability to browse the Web because  of the routing it does. Not normally an
issur, but it happens sometimes. Generally you want the victim box to be a
different VM or host.

That said there seem to be a bunch of things going on there. I'll try to
recreate the problem at home tonight and push out a solution that
definately works on Kali 2.0 by end of day. I'm sorry it's given you so
much trouble. Hopefully we can fix it up and keep hacking!

I'll let you know as soon as I've solved the problems!

- 0sm0s1z

**Comment by SERAF000VIRUS** [comment]
yep, on ''bridged adapter ''  mode

works best on nat mode, but like u said, cant attack other computers,etc...

cant wait to u guys fix all of this to get working on kali 2.0

plus my normal internet doesn't work on on "bridged adapter" mode !!!
